### ISSUE TITLE
Can't import the named export 'EventEmitter' from non EcmaScript module

### ISSUE THREAD

**Issue by scenaristeur** [JordanShurmer/vue-solid-plugin#4]
hi @JordanShurmer 
i've just installed for https://scenaristeur.github.io/shighl-vuejs/ but i got this error : 

```
Failed to compile.

./node_modules/asynciterator/asynciterator.mjs 65:35-47
Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)
```
![image](https://user-images.githubusercontent.com/4020744/88463909-9a850500-ceb6-11ea-9a2f-702f103b5461.png)

Do you have any idea ? 
Thxs

**Comment by JordanShurmer** [comment]
Hey! Glad to see that this may be useful to you. Hopefully using it will make sense to you and bring actual benefit to you project. Please reach out as needed, with problems, ideas, etc.

As for this issue.. I have not seen that exact problem before. I can get on today and see if I can replicate the problem.

**Comment by scenaristeur** [comment]
THxs ;-) if you want to look more at my code, here is where i plan to put it https://github.com/scenaristeur/shighl-vuejs/blob/4470f269139c6f2df75708ae9f7a154a5a76e356/src/components/LoadShape.vue#L4

**Comment by scenaristeur** [comment]
This repo could interest you
https://github.com/scenaristeur/ovc-jv
Building autonomous webcomponents that communicate with Vuex

**Comment by ZeeshanJan** [comment]
I am facing the same problem/issue. 

`Can't import the named export 'EventEmitter' from non EcmaScript module (only default export is available)`

@scenaristeur - Please share if you have found any workaround.
